-- Carga inicial: os links que antes ficavam no data.js.
insert into public.links (name, url, category, description, tags, approved, created_at) values
  ('SmoothUI', 'https://smoothui.dev/', 'ui', 'Biblioteca com 130 componentes React animados, feitos como “drop-in replacement” do shadcn/ui, com Motion, Tailwind, blocks, templates e integração com IA.', array['React','Componentes','Animação','Tailwind','shadcn','IA']::text[], true, now() - interval '1 day' + interval '0 seconds'),
  ('beUI', 'https://beui.dev', 'ui', 'Biblioteca open source de componentes animados para React/Next.js, usando Motion + Tailwind. Permite copiar e colar ou instalar via shadcn CLI.', array['React','Componentes','Animação','Tailwind','shadcn','Open source']::text[], true, now() - interval '1 day' + interval '1 seconds'),
  ('reactbites.dev', 'https://reactbites.dev', 'ui', 'Coleção de componentes e snippets para React.', array['React','Componentes','Snippets']::text[], true, now() - interval '1 day' + interval '2 seconds'),
  ('21st.dev', 'https://21st.dev/', 'ui', 'Biblioteca de componentes e recursos de UI para desenvolvimento com IA.', array['React','Componentes','IA']::text[], true, now() - interval '1 day' + interval '3 seconds'),
  ('Forma — Icon Creator', 'https://iconcreator.dev/', 'ui', 'Ferramenta para criar e customizar ícones usando Tabler, Lucide, Phosphor, Iconoir e Heroicons, com exportação para SVG ou PNG.', array['Ícones','Ferramenta','SVG']::text[], true, now() - interval '1 day' + interval '4 seconds'),
  ('Design Spells', 'https://designspells.com/', 'ui', 'Curadoria de microinterações e detalhes de UI para criar interfaces mais refinadas.', array['Inspiração','Microinterações','Curadoria']::text[], true, now() - interval '1 day' + interval '5 seconds'),
  ('Inspora', 'https://www.inspora.design/', 'ui', 'Referências e inspiração para design de interfaces.', array['Inspiração','Curadoria']::text[], true, now() - interval '1 day' + interval '6 seconds'),
  ('Motion Sites', 'https://motionsites.ai/', 'ui', 'Galeria e referências de sites com foco em motion design.', array['Inspiração','Animação','Galeria']::text[], true, now() - interval '1 day' + interval '7 seconds'),
  ('Isocons', 'https://www.isocons.app/', 'ui', 'Biblioteca de ícones isométricos.', array['Ícones','3D']::text[], true, now() - interval '1 day' + interval '8 seconds'),
  ('Kinetics — Colorion', 'https://kinetics.colorion.co/', 'motion', 'Efeitos de motion open source, fáceis de copiar e usar.', array['Animação','Efeitos','Open source']::text[], true, now() - interval '1 day' + interval '9 seconds'),
  ('Animated Buttons — Colorion', 'https://animatedbuttons.colorion.co/', 'motion', 'Coleção de botões CSS animados.', array['Animação','CSS','Botões']::text[], true, now() - interval '1 day' + interval '10 seconds'),
  ('Anthropic Skills', 'https://github.com/anthropics/skills', 'skills', 'Repositório oficial de exemplos de Skills para o Claude: pastas com instruções e scripts que ensinam o agente a executar tarefas específicas de forma repetível.', array['Skills','Claude','Agentes','Open source']::text[], true, now() - interval '1 day' + interval '11 seconds')
on conflict (lower(url)) do nothing;
